### ISSUE TITLE
[Additional Info] License Manager

### ISSUE THREAD

**Issue by dennyamarojr** [simeononsecurity/Windows-Optimize-Debloat#1]
Hi simeononsecurity,

Just here for put an additional info about the restrict license manager, in case for users has problem in Microsoft Store are not downloadings apps is because License Manager is disabled.

Will appear the following message
![Ett_8OyXAAMqUvd](https://user-images.githubusercontent.com/36896116/107283968-f148cb00-6a11-11eb-984b-0021ab7d4d35.jpg)

As you can see in the picture, Windows Update is Enabled but in Microsoft Store says Windows Update is Disabled. To fix this problem, go to services.msc and search for Windows License Manager Service and them change the Startup type from Disabled to Automatic and them apply and them click Start (to the service start running). After doing this, you should be able to download the apps again.

**Comment by simeononsecurity** [comment]
Thanks @dennyamarojr , I was unaware of this issue. I have not run into this myself.
I'll update the repo with a fix included.

**Comment by simeononsecurity** [comment]
Added
```powershell
    Set-Service -Name "LicenseManager" -StartupType "Automatic"
    Start-Service -Name "LicenseManager"
```
https://github.com/simeononsecurity/Windows-Optimize-Debloat/commit/c088382f67ea7708277f7c9a5c7d6bb22aaab475

**Comment by simeononsecurity** [comment]
Well, after looking, I lumped the gun on my fix. 
Thanks for the info @dennyamarojr , I wasn't aware of this issue.
