### ISSUE TITLE
remove

### ISSUE THREAD

**Issue by YashSoPro** [simeononsecurity/Windows-Optimize-Debloat#12]
**Describe the bug**
how to remove it pls help

**Comment by YashSoPro** [comment]
> Message that will be displayed on users' first issue

what?

**Comment by simeononsecurity** [comment]
@YashSoPro 

Please follow the documentation here
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/wiki/How-to-Reverse-the-Changes-performed-in-Windows%E2%80%90Optimize%E2%80%90Harden%E2%80%90Debloat
