### ISSUE TITLE
I lost ability to access shared folders on local network after applying the script

### ISSUE THREAD

**Issue by Frank-H-314** [simeononsecurity/Windows-Optimize-Debloat#14]
Is there any way to fix the problem?

**Comment by simeononsecurity** [comment]
The script shouldn't interfere with network folders. But if you wanted to check some things, I would verify the following.

#### 1. Enable File and Printer Sharing Services
1. **Open Control Panel:**
   - Press `Windows + R` to open the Run dialog box.
   - Type `control` and press `Enter`.

2. **Network and Sharing Center:**
   - In the Control Panel, navigate to `Network and Internet` and then `Network and Sharing Center`.

3. **Change Advanced Sharing Settings:**
   - On the left side, click on `Change advanced sharing settings`.

4. **Turn on File and Printer Sharing:**
   - Expand the profile you want to configure (e.g., Private, Guest or Public).
   - Select `Turn on file and printer sharing`.
   - Click `Save changes`.

#### 2. Revert Changes Made by Script #14
Assuming script #14 made specific changes that need to be reverted to enable file and printer sharing, here’s a general approach:

1. **Identify Changes:**
   - Review script #14 to identify what modifications it made. Common changes might include altering firewall rules, network settings, or disabling specific services.

2. **Undo Firewall Changes:**
   - Open the Command Prompt as an Administrator.
     - Press `Windows + X` and select `Command Prompt (Admin)` or `Windows PowerShell (Admin)`.
   - To allow file and printer sharing through the firewall, run the following commands:
     ```sh
     netsh advfirewall firewall set rule group="File and Printer Sharing" new enable=Yes
     ```

3. **Restore Network Settings:**
   - If the script modified network adapter settings, you can reset them:
     - Open Command Prompt as an Administrator.
     - Run the following commands:
       ```sh
       netsh int ip reset
       netsh winsock reset
       ```

4. **Start Network Services:**
   - Open the Services Manager.
     - Press `Windows + R`, type `services.msc`, and press `Enter`.
   - Locate the following services and ensure they are running. If they are stopped, right-click on each service and select `Start`:
     - `Function Discovery Resource Publication`
     - `SSDP Discovery`
     - `UPnP Device Host`

5. **Reboot Your System:**
   - Restart your computer to apply the changes.

#### 3. Verify Access to Shared Folders
- After performing the steps above, verify if you can access the shared folders on your local network:
  - Open File Explorer.
  - Navigate to `Network` and check if the shared folders are accessible.

**Comment by simeononsecurity** [comment]
Closing due to lack of response
