### ISSUE TITLE
Stop-process syntax error

### ISSUE THREAD

**Issue by rsb-23** [simeononsecurity/Windows-Optimize-Debloat#2]
command = `Stop-Process -Force -Force -Name "OneDrive.exe"`
error = Stop-Process : Cannot bind parameter because parameter 'Force' is specified more than once. 

Please rectify `-Force -Force` all 5 occurrences to `-Force`

**Comment by simeononsecurity** [comment]
Ooh good catch. 
Must've been a copy replace error
