### ISSUE TITLE
Lot of bugs

### ISSUE THREAD

**Issue by mrbateuk** [simeononsecurity/Windows-Optimize-Debloat#6]
Hi there

After installing the scripts, I had no accesss to screeen and sleep ( I want to remove group policy, how to do that ?)

the snipping tool also was not saved in screenshot folder ? why ?

Can you help me out to fix those bugs ?

**Comment by simeononsecurity** [comment]
> Hi there
> 
> After installing the scripts, I had no accesss to screeen and sleep ( I want to remove group policy, how to do that ?)
> 

Please review the documentation to adjust those settings
- https://github.com/simeononsecurity/Windows-Optimize-Debloat/blob/main/README.md#editing-policies-in-local-group-policy-after-the-fact
- https://techcommunity.microsoft.com/t5/ask-the-directory-services-team/managing-power-with-group-policy-part-1-of-3/ba-p/395121

> the snipping tool also was not saved in screenshot folder ? why ?

We're not sure what you mean here, can you elaborate?. Try using the `Win + Shift + S` shortcut to the screenshot tool instead.

**Comment by mrbateuk** [comment]
Hi
I want to remove those in firefox, chrome, internet explorer

<a href="https://ibb.co/YW72fs0"><img src="https://i.ibb.co/vBx1LnX/Screenshot-2023-10-15-225708.png" alt="Screenshot-2023-10-15-225708" border="0"></a>

It's so annoying

**Comment by simeononsecurity** [comment]
> Hi I want to remove those in firefox, chrome, internet explorer
> 
> [![Screenshot-2023-10-15-225708](https://camo.githubusercontent.com/6d88341cf55a29629ee535e6bdfcb0c0213021ea09d85c1f8afdda2af9bcc891/68747470733a2f2f692e6962622e636f2f764278314c6e582f53637265656e73686f742d323032332d31302d31352d3232353730382e706e67)](https://ibb.co/YW72fs0)
> 
> It's so annoying

Please review the readme
The instructions to modify those options is in 
https://github.com/simeononsecurity/Windows-Optimize-Debloat#additions-notable-changes-and-bugfixes

Additionally, this topic is closed. Please open a new issue if you're having new issues. Otherwise, please open a discussion if you have questions.
